name: Formatting Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual:
        description: "Trigger the workflow manually"
        required: false

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make deps

      - name: Check Formatting
        run: |
          make fmt-check
